### ISSUE TITLE
Error C3861 and support c++11

### ISSUE THREAD

**Issue by FrankXie05** [RealTimeChris/Jsonifier#2]
In the latest [commit ](https://github.com/RealTimeChris/Jsonifier/commit/bc26329c6274ad77ba341fdbd2c0102e431f606d#diff-61e9dd7376d67ec49a59056aebcebd20a1317021029410456434e069d58c1fba) you seem to have removed the use of `_addcarry_u64`.
`to_underlying` was introduced in `C++11`, in the header file `<type_traits>`.

```
E:\bug\vcpkg\installed\x64-windows\include\jsonifier/Simd.hpp(157): error C3861: '_addcarry_u64': identifier not found
E:\bug\vcpkg\installed\x64-windows\include\jsonifier/Parse_Impl.hpp(52): error C2039: 'to_underlying': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\codecvt(23): note: see declaration of 'std'
```
[install-x64-windows-dbg-out.log](https://github.com/RealTimeChris/Jsonifier/files/11661511/install-x64-windows-dbg-out.log)

**Comment by RealTimeChris** [comment]
Does it work with the latest version? v0.9.5

**Comment by FrankXie05** [comment]
@RealTimeChris 
```
PS E:\update\vcpkg> ./vcpkg install jsonifier:x64-windows
Computing installation plan...
The following packages will be built and installed:
    jsonifier[core]:x64-windows -> 0.9.5
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from E:\Binarycache in 265 us. Use --debug to see more details.
Installing 1/1 jsonifier:x64-windows...
Building jsonifier[core]:x64-windows...
-- Downloading https://github.com/realtimechris/jsonifier/archive/v0.9.5.tar.gz -> realtimechris-jsonifier-v0.9.5.tar.gz...
-- Extracting source E:/update/vcpkg/downloads/realtimechris-jsonifier-v0.9.5.tar.gz
-- Using source at E:/update/vcpkg/buildtrees/jsonifier/src/v0.9.5-e697a692d5.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: E:/update/vcpkg/packages/jsonifier_x64-windows/share/jsonifier/copyright
-- Performing post-build validation
Stored binaries in 1 destinations.
Elapsed time to handle jsonifier:x64-windows: 11 s
Total install time: 17 s
jsonifier provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(Jsonifier CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Jsonifier::Jsonifier)

PS E:\update\vcpkg> ./vcpkg install discordcoreapi:x64-windows
Computing installation plan...
The following packages will be built and installed:
    discordcoreapi[core]:x64-windows -> 1.60
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from E:\Binarycache in 257 us. Use --debug to see more details.
Installing 1/1 discordcoreapi:x64-windows...
Building discordcoreapi[core]:x64-windows...
-- Using cached RealTimeChris-DiscordCoreAPI-cdadcb90d87c38a051aea8e7311e4f3e6053ed81.tar.gz.
-- Cleaning sources at E:/update/vcpkg/buildtrees/discordcoreapi/src/3e6053ed81-7ffb7c7f1e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/update/vcpkg/downloads/RealTimeChris-DiscordCoreAPI-cdadcb90d87c38a051aea8e7311e4f3e6053ed81.tar.gz
-- Using source at E:/update/vcpkg/buildtrees/discordcoreapi/src/3e6053ed81-7ffb7c7f1e.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: E:/update/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: E:/update/vcpkg/buildtrees/discordcoreapi/x64-windows-dbg
    See logs for more information:
      E:\update\vcpkg\buildtrees\discordcoreapi\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/discordcoreapi/portfile.cmake:17 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)


error: building discordcoreapi:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+discordcoreapi
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[discordcoreapi]+Build+error&body=Copy+issue+body+from+E%3A%2Fupdate%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

PS E:\update\vcpkg>
```
Exactly the same error log：
https://github.com/RealTimeChris/DiscordCoreAPI/issues/32#issuecomment-1635363361

**Comment by FrankXie05** [comment]
BTW, It is fully working on vs2022, it builds very well.

**Comment by RealTimeChris** [comment]
> BTW, It is fully working on vs2022, it builds very well.

So it's just vs2019 that it's not working on? Do I need to support vs2019?

**Comment by FrankXie05** [comment]
@RealTimeChris vcpkg supports all versions after `VS 2015` by default. https://github.com/microsoft/vcpkg#:~:text=Visual%20Studio%202015%20Update%203%20or%20greater%20with%20the%20English%20language%20pack

**Comment by FrankXie05** [comment]
We still hope to support it. Most users may use the 2019 version, and there are also many 2017 versions. On the contrary, the proportion of 2022 is a little less. 🫤

**Comment by RealTimeChris** [comment]
It seems the issue is from C++23 not being enabled? Although I've set the c++latest compiler option.

**Comment by RealTimeChris** [comment]
> We still hope to support it. Most users may use the 2019 version, and there are also many 2017 versions. On the contrary, the proportion of 2022 is a little less. 🫤

Alright try it with the latest pushes of Jsonifier and DiscordCoreAPI - it should build.

**Comment by FrankXie05** [comment]
2019 does not support c++23
https://learn.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-160

**Comment by RealTimeChris** [comment]
> 2019 does not support c++23 https://learn.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-160

Alright try it with the latest pushes of Jsonifier and DiscordCoreAPI - it should build.

**Comment by FrankXie05** [comment]
If this version is pushed to `vcpkg`, it can be checked by ci. Because our ci uses the 2022 version. But this means that this port only supports the 2022 version of vs.
https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/windows/bootstrap-from-source.cmd

**Comment by RealTimeChris** [comment]
> If this version is pushed to `vcpkg`, it can be checked by ci. Because our ci uses the 2022 version. But this means that this port only supports the 2022 version of vs. https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/windows/bootstrap-from-source.cmd

I removed the std::to_underlying calls - it should build with C++20 now.

**Comment by FrankXie05** [comment]
@RealTimeChris Need to update the content of the compressed package of the released new version. :)

**Comment by RealTimeChris** [comment]
What do you mean? The source files that are released?
